name: Framework

on:
  pull_request:
    branches:
      - main
      - release-2.[7-9]

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@reusable-kind-workflow
    with:
      hub_only_component: 'true'
