name: Framework

on:
  pull_request:
    branches:
      - main
      - release-2.[7-9]

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@d601ac6c1ba726c34ac4728fe3eff485d3324f87
    with:
      hub_only_component: 'true'
