name: Framework

on:
  pull_request:
    branches:
      - main
      - release-2.[7-9]

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@9016260c57d66f65deae9e50dfac48a667550981
    with:
      hub_only_component: 'true'
