name: Framework

on:
  pull_request:
    branches:
      - main
      - release-2.[7-9]

jobs:
  fw-kind-tests:
    name: KinD
    uses: JustinKuli/governance-policy-framework/.github/workflows/kind.yml@ecbd83b884d091d5a40b3724d034936003fee7a6
    with:
      hub_only_component: 'true'
